---
title: "Playing Type-I Detective"
author: "ML"
date: "2024-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


#remotes::install_github("bips-hb/cpi@x_tilde_list")
#remotes::install_github("markusloecher/cpi_markus@x_tilde_list")
#remotes::install_github("markusloecher/cpi_markus")

library(cpi)
stopifnot(packageVersion("cpi") == "0.1.5.1")#Markus version
library(mlr3)
library(mlr3learners)
library(ranger)

library(here)
#source(here("explore/utils.R")) 
source("~/Documents/GitHub/pfiarf/explore/problems.R")
library(ggpubr)
library(ggplot2)
library(mvtnorm)
rerun=FALSE
```


```{r}
#Small test example:
tmp = cpi(task = tsk("mtcars"), learner = lrn("regr.lm"), 
           resampling = rsmp("holdout"))
```

## "Regular" Permutation Importance First

```{r}
nCores = 50
num_replicates <- 500 #10000
n <- 1000;n_train = round(n*2/3);n_test = round(n*1/3)
p <- 10
cov_base <- .5 # 
dg = "nonlinear_data"#data generation


XY_train = linear_data(n=n_train, p=p, outcome = "regr", cov_base = cov_base)
XY_test = linear_data(n=n_test, p=p, outcome = "regr", cov_base = cov_base)
    
```

```{r}

compute_MDA = function(n =1000,p=10, cov_base = .5){
  n_train = round(n*2/3);n_test = round(n*1/3)
  XY_train = linear_data(n=n_train, p=p, outcome = "regr", cov_base = cov_base)
  XY_test = linear_data(n=n_test, p=p, outcome = "regr", cov_base = cov_base)

  rf = ranger(y ~ ., data = XY_train, num.trees = 200, importance = 'permutation')
  yHat = predict(rf, XY_test)
  MSE_orig = (yHat$predictions-XY_test[,"y"])^2
  MDA = MDA_se = rep(0,p)
  
  for (j in 1:p){
    XY_test_perm = XY_test
    XY_test_perm[,j] = sample(XY_test_perm[,j])
    yHat_perm = predict(rf, XY_test_perm)
    MSE_perm = (yHat_perm$predictions-XY_test[,"y"])^2
    MDA[j] = mean(MSE_perm-MSE_orig)
    MDA_se[j] = sd(MSE_perm-MSE_orig)/ sqrt(nrow(XY_test))
  }
  
  PermIMP =c(MDA, MDA_se, rf$variable.importance)
  names(PermIMP) = c(paste0("MDA_x",1:p),paste0("MDA_se_x",1:p),paste0("MDA_oob_x",1:p))

  return(PermIMP)

}

compute_MDA()
```

```{r, eval=rerun}

set.seed(123)
num_replicates <- 500 #
MDA_dist = matrix(0,nrow=num_replicates, ncol=3*p)
colnames(MDA_dist) = c(paste0("MDA_x",1:p),paste0("MDA_se_x",1:p),paste0("MDA_oob_x",1:p))

for (i in 1:num_replicates) {
  MDA_dist[i,]= compute_MDA()
}
save(MDA_dist, file = "MDA_dist.rda")
```

```{r, echo=F, eval=!rerun}
load("MDA_dist.rda")
colnames(MDA_dist) = c(paste0("MDA_x",1:p),paste0("MDA_se_x",1:p))#,paste0("MDA_oob_x",1:p))

```


```{r, echo = F}
MDA_dist_long <- as.data.frame(MDA_dist[,c(1:10)]) %>% 
    tidyr::pivot_longer(
      cols = 1:10, 
      names_to = "Variable",
      values_to = "MDA"
    )
MDA_dist_long$Variable = gsub("MDA_","",MDA_dist_long$Variable)
MDA_dist_long$Variable = factor(MDA_dist_long$Variable, levels = paste0("x",1:p))
MDA_dist_long$validation = "test"

MDA_dist_long_oob <- as.data.frame(MDA_dist[,c(21:30)]) %>% 
    tidyr::pivot_longer(
      cols = 1:10, 
      names_to = "Variable",
      values_to = "MDA"
    )
MDA_dist_long_oob$Variable = gsub("MDA_oob_","",MDA_dist_long_oob$Variable)
MDA_dist_long_oob$Variable = factor(MDA_dist_long_oob$Variable, levels = paste0("x",1:p))
MDA_dist_long_oob$validation = "oob"

MDA_dist_long = rbind.data.frame(MDA_dist_long,MDA_dist_long_oob)


```
```{r}
gp = ggplot(MDA_dist_long, aes(x = Variable, y = MDA, fill=validation)) +
    geom_boxplot(outlier.size = .01) +
    #facet_grid(Problem ~ Learner, scales = "free") +
    geom_hline(yintercept = 0, col = "red") +
    xlab("Variable") + ylab("MDA ") +
    theme_bw()+ ggtitle("(Unconditional) Permutation importance", subtitle = "Linear Data")
gp
```


```{r, echo=F, eval=F}
MDA_dist[,"Statistic"] = MDA_dist[]
ggplot(MDA_dist, aes(Statistic)) +
    geom_histogram(aes(y = ..density..), bins = 100) +
    facet_grid(Problem ~ Learner) +
    stat_function(fun = dt, color = 'red', args = list(df = unique(res$n) - 1)) +
    xlab("Test statistic") + ylab("Density") +
    theme_bw()
```


