---
title: "Unconditional Permutation importance"
author: "ML"
date: "2024-03-06"
output:
  html_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F)


#remotes::install_github("bips-hb/cpi@x_tilde_list")
#remotes::install_github("markusloecher/cpi_markus@x_tilde_list")
#remotes::install_github("markusloecher/cpi_markus")

library(cpi)

library(mlr3)
library(mlr3learners)
library(ranger)

library(here)
#source(here("explore/utils.R")) 
source("~/Documents/GitHub/pfiarf/explore/utils.R")
source("~/Documents/GitHub/pfiarf/explore/problems.R")
library(ggpubr)
library(ggplot2)
library(mvtnorm)
rerun=FALSE

if (rerun) stopifnot(packageVersion("cpi") == "0.1.5.1")#Markus version
```

```{r, eval=FALSE}
#Small test example:
tmp = cpi(task = tsk("mtcars"), learner = lrn("regr.lm"), 
           resampling = rsmp("holdout"))
```

# "Regular" Permutation Importance

```{r}
nCores = 50
num_replicates <- 500 #10000
n <- 1000;n_train = round(n*2/3);n_test = round(n*1/3)
p <- 10
cov_base <- .5 # 
dg = "linear_data"#data generation

XY_train = linear_data(n=n_train, p=p, outcome = "regr", cov_base = cov_base)
XY_test = linear_data(n=n_test, p=p, outcome = "regr", cov_base = cov_base)
    
```

```{r, eval=F}
#testing:
compute_MDA()

compute_MDA_reps(num_replicates = 5, 
                            n =n,p=p, cov_base = cov_base,
                            nCores = 5,
                            outFile = "tmp.rda")
```

```{r, eval=rerun}

set.seed(123)
num_replicates <- 500 #
MDA_dist = matrix(0,nrow=num_replicates, ncol=3*p)
colnames(MDA_dist) = c(paste0("MDA_x",1:p),paste0("MDA_se_x",1:p),paste0("MDA_oob_x",1:p))

for (i in 1:num_replicates) {
  MDA_dist[i,]= compute_MDA()
}
runPars = list(n=n, p=p, outcome = "regr", cov_base = cov_base)
save(MDA_dist, runPars, file = "MDA_lin_reg.rda")
```

```{r, eval=rerun}
# Independent Features
nCores = 50;num_replicates <- 10000
n <- 1000;p <- 10;cov_base <- 0
outFile = paste0("MDA_lin_00.rda")
compute_MDA_reps(num_replicates = num_replicates, 
                            n =n,p=p, cov_base = cov_base,
                            nCores = nCores,
                            outFile = outFile)
```

```{r, eval=rerun}
# Toeplitz
nCores = 50;num_replicates <- 10000
n <- 1000;p <- 10;cov_base <- 0.5
outFile = paste0("MDA_lin_05.rda")
compute_MDA_reps(num_replicates = num_replicates, 
                            n =n,p=p, cov_base = cov_base,
                            nCores = nCores,
                            outFile = outFile)
```

```{r, echo=F, eval=!rerun}
#load("MDA_lin_reg.rda",verbose=TRUE)
#MDA_dist = cbind.data.frame(MDA_dist, MDA_dist[,1:10]/MDA_dist[,11:20])
#colnames(MDA_dist) = c(paste0("MDA_x",1:p),paste0("MDA_se_x",1:p),paste0("MDA_oob_x",1:p),paste0("MDA_t-score_x",1:p))
#save(MDA_dist,file="MDA_lin_reg.rda")
```

## Independent Features

```{r}
#load("MDA_lin_00.rda")
#plotSDImp(MDA_dist[,c(31:40)], values_to = "t_score", main = "Ind. Features")
```

```{r, fig.width=10, fig.height=4}
load("MDA_lin_00.rda")
g1 = plotSDImp(MDA_dist[,c(31:40)], values_to = "t_score", sub ="t-score",main="", vertLine=1.65)
g2 = plotSDImp(MDA_dist[,c(1:10)], values_to = "MDA", sub ="MDA",main="")
gg = ggarrange(g1,g2,nrow=1)
annotate_figure(gg, top = text_grob("Independent Features", 
               color = "darkblue", face = "bold", size = 14))
```

## Original Toeplitz

```{r, fig.width=10, fig.height=4}
load("MDA_lin_reg.rda")
g1 = plotSDImp(MDA_dist[,c(31:40)], values_to = "t_score", sub ="t-score",main="", vertLine=1.65)
g2 = plotSDImp(MDA_dist[,c(1:10)], values_to = "MDA", sub ="MDA",main="")
gg = ggarrange(g1,g2,nrow=1)
annotate_figure(gg, top = text_grob("Toeplitz (rho=0.5)", 
               color = "darkblue", face = "bold", size = 14))
```

```{r, eval=FALSE}
#Why is there an apparent mean shift when standardizing?
print(mean(MDA_dist[,"MDA_x1"]))
print(mean(MDA_dist[,"MDA_x1"])/sd(MDA_dist[,"MDA_x1"]))
print(mean(MDA_dist[,"MDA_t-score_x1"]))
```

## Alternating Toeplitz, RF

```{r lin_alt, eval=rerun}
set.seed(123)
num_replicates <- 1000 #
MDA_dist = matrix(0,nrow=num_replicates, ncol=3*p)
colnames(MDA_dist) = c(paste0("MDA_x",1:p),paste0("MDA_se_x",1:p),paste0("MDA_oob_x",1:p))

beta = rep(seq(0, .9, length.out = 10), each = p/10)
beta[seq(1,10,by=2)]=0

for (i in 1:num_replicates) {
  MDA_dist[i,]= compute_MDA(beta=beta)
}
save(MDA_dist, file = "MDA_lin_alt.rda")
```

```{r, eval=rerun}
# Toeplitz
nCores = 50;num_replicates <- 1000
n <- 1000;p <- 10;cov_base <- 0.5
beta = rep(seq(0, .9, length.out = 10), each = p/10)
beta[seq(1,10,by=2)]=0

outFile = paste0("MDA_lin_alt.rda")
compute_MDA_reps(num_replicates = num_replicates, 
                            n =n,p=p, cov_base = cov_base,
                            beta=beta,
                            nCores = nCores,
                            outFile = outFile)
```

```{r, fig.width=10, fig.height=4}
load("MDA_lin_alt.rda")
g1 = plotSDImp(MDA_dist[,c(31:40)], values_to = "t_score", sub ="t-score",main="", vertLine=1.65)
g2 = plotSDImp(MDA_dist[,c(1:10)], values_to = "MDA", sub ="MDA",main="")
gg = ggarrange(g1,g2,nrow=1)
annotate_figure(gg, top = text_grob("Alternating Toeplitz (rho=0.5)", 
               color = "darkblue", face = "bold", size = 14))
```

```{r}
plot(colMeans(MDA_dist[,c(31:40)]>1.65), pch=20,col="blue",main="Rejection Rate", ylab = "t-score>1.65", ylim = c(0,1));grid()
abline(h=0.05,col=2,lty=2)
```

## Alternating Toeplitz, RF, mtry=1


## Alternating Toeplitz, LM


```{r, eval=rerun}
# Toeplitz
nCores = 1;num_replicates <- 1000
n <- 1000;p <- 10;cov_base <- 0.5
beta = rep(seq(0, .9, length.out = 10), each = p/10)
beta[seq(1,10,by=2)]=0

outFile = paste0("MDA_lin_alt_LM.rda")
compute_MDA_reps(num_replicates = num_replicates, 
                            n =n,p=p, cov_base = cov_base,
                            beta=beta,
                            nCores = nCores,
                            learner = "LM",
                            outFile = outFile)
```

```{r, fig.width=10, fig.height=4}
load("MDA_lin_alt_LM.rda")
g1 = plotSDImp(MDA_dist[,c(31:40)], values_to = "t_score", sub ="t-score",main="", vertLine=1.65)
g2 = plotSDImp(MDA_dist[,c(1:10)], values_to = "MDA", sub ="MDA",main="")
gg = ggarrange(g1,g2,nrow=1)
annotate_figure(gg, top = text_grob("Alternating Toeplitz (rho=0.5), LM", 
               color = "darkblue", face = "bold", size = 14))
```

```{r}
plot(colMeans(MDA_dist[,c(31:40)]>1.65), pch=20,col="blue",main="Rejection Rate", ylab = "t-score>1.65", ylim = c(0,1));grid()
abline(h=0.05,col=2,lty=2)
```


# CPI (ARF)

```{r}

```

## Alternating Toeplitz

```{r, fig.width=10, fig.height=4}
#load("CPI_lin_alt.rda")
load("CPI_alt_lin_rf.rda")
g1 = plotSDImp(MDA_dist[,c(31:40)], values_to = "t_score", sub ="t-score",main="", vertLine=1.65)
g2 = plotSDImp(MDA_dist[,c(1:10)], values_to = "MDA", sub ="MDA",main="")
gg = ggarrange(g1,g2,nrow=1)
annotate_figure(gg, top = text_grob("Alternating Toeplitz (rho=0.5)", 
               color = "darkblue", face = "bold", size = 14))
```

------------------------------------------------------------------------

```{r, echo = F, eval=FALSE}
MDA_dist_long <- as.data.frame(MDA_dist[,c(1:10)]) %>% 
    tidyr::pivot_longer(
      cols = 1:10, 
      names_to = "Variable",
      values_to = "MDA"
    )
MDA_dist_long$Variable = gsub("MDA_","",MDA_dist_long$Variable)
MDA_dist_long$Variable = factor(MDA_dist_long$Variable, levels = paste0("x",1:p))
MDA_dist_long$validation = "test"

MDA_dist_long_oob <- as.data.frame(MDA_dist[,c(21:30)]) %>% 
    tidyr::pivot_longer(
      cols = 1:10, 
      names_to = "Variable",
      values_to = "MDA"
    )
MDA_dist_long_oob$Variable = gsub("MDA_oob_","",MDA_dist_long_oob$Variable)
MDA_dist_long_oob$Variable = factor(MDA_dist_long_oob$Variable, levels = paste0("x",1:p))
MDA_dist_long_oob$validation = "oob"

MDA_dist_long = rbind.data.frame(MDA_dist_long,MDA_dist_long_oob)

```

```{r, eval=FALSE}
gp = ggplot(MDA_dist_long, aes(x = Variable, y = MDA, fill=validation)) +
    geom_boxplot(outlier.size = .01) +
    #facet_grid(Problem ~ Learner, scales = "free") +
    geom_hline(yintercept = 0, col = "red") +
    xlab("Variable") + ylab("MDA ") +
    theme_bw()+ ggtitle("(Unconditional) Permutation importance", 
                subtitle = "Linear Data, regular beta")
gp
```

```{r, echo=F, eval=F}
MDA_dist = as.data.frame(MDA_dist)
MDA_dist$Statistic = as.numeric(MDA_dist[,"MDA_x1"]/MDA_dist[,"MDA_se_x1"])
dof =  nrow(XY_test) - 1

ggplot(MDA_dist, aes(Statistic)) +
    geom_histogram(aes(y = ..density..), bins = 50) +
    stat_function(fun = dt, color = 'red', args = list(df = dof)) +
    xlab("Test statistic") + ylab("Density") +
    theme_bw()

mean(MDA_dist$Statistic > qt(0.975,dof))
```
